### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [yuuta1219/rubychan#1]
遅くなってしまい申し訳ございません。。
※ 確認後closeしていただければと思います。

## サービスレビュー

* キャラクターが教えてくれる発想は面白いと思います。
* 実態がただの検索サービスになってしまっていてコードも単純になってしまうと思うので、もう少し色々な機能拡張を考えてみていただけるといいのかなと思いました。
* LINEボットでもいいですし、LINEボット風のUIでもいいので、猫との対話感を出していくのもいいですね。

## コードレビュー

https://github.com/yuuta1219/rubychan/blob/c2b63a7140207c2f230214cf9a56984cdcd5b81a/app/controllers/libraries_controller.rb#L6

1という固定値をそのまま書くことをマジックナンバーと言って基本的には推奨されていません。モデルなどに定数化させて参照する形がいいかなと思います。

https://github.com/yuuta1219/rubychan/blob/c2b63a7140207c2f230214cf9a56984cdcd5b81a/app/controllers/quizzes_controller.rb#L6

こちらでクラス変数使う必要ってありますかね？？モデルやPORO（Plain-Old Ruby Object）ではたまに見かけますが、controllerでクラス変数を使う理由があまりないかなと思ったので。answerで使いまわししたいのであればbefore_actionなどで共通処理にしてしまってインスタンス変数にいれる形がよいかと思います。

https://github.com/yuuta1219/rubychan/blob/c2b63a7140207c2f230214cf9a56984cdcd5b81a/app/controllers/quizzes_controller.rb#L25-L36

処理が冗長ですね。選択肢すべてとanswerをpostすればもう少し処理もすっきり書けるかなと思います。

https://github.com/yuuta1219/rubychan/blob/c2b63a7140207c2f230214cf9a56984cdcd5b81a/config/routes.rb#L18-L28

URL設計が冗長なので
```
resources :akashic_records, param: :tag_name
```
とやっておくと `/akashic_records/ruby` と書いたときにshowメソッドでparams[:tag_name]で呼び出せますよ

* Railsガイドを改めて読まれると上記のようなことが書いてあるので、改めて読んでいただけたらと思います。

**Comment by yuuta1219** [comment]
ありがとうございます！
